const path = require('path');
const sqlite3 = require(path.join(process.cwd(), 'node_modules', 'sqlite3')).verbose();
const db = new sqlite3.Database('./fund_simulator.db');
const q = (sql, p = []) => new Promise((res, rej) => db.all(sql, p, (e, r) => e ? rej(e) : res(r || [])));
(async () => {
  const userId = 'default';
  const periodStart = '2026-09-11';
  const snapWeek = await q('SELECT date, daily_pnl FROM portfolio_daily WHERE user_id = ? AND date >= ? ORDER BY date', [userId, periodStart]);
  console.log('期间快照:', JSON.stringify(snapWeek));
  const realized = await q('SELECT amount FROM realized_pnl WHERE user_id = ? AND created_at >= datetime(?)', [userId, periodStart + ' 00:00:00']);
  console.log('已实现盈亏:', JSON.stringify(realized));
  const wl = await q('SELECT COUNT(*) c FROM watchlist WHERE user_id = ?', [userId]);
  console.log('观察池:', JSON.stringify(wl));
  const trades = await q("SELECT transaction_type FROM transactions WHERE user_id = ? AND transaction_date >= date(?)", [userId, periodStart]);
  const buys = trades.filter(t => t.transaction_type === 'BUY').length;
  const sells = trades.filter(t => t.transaction_type === 'SELL').length;
  console.log('期间交易 买:', buys, '卖:', sells);
  const snapSum = snapWeek.reduce((a, x) => a + (x.daily_pnl || 0), 0);
  console.log('本周合计:', snapSum.toFixed(2), '→ AI点评:', snapSum >= 100 ? '表现积极' : snapSum >= 0 ? '小幅盈利' : snapSum >= -100 ? '小幅回撤' : '回撤明显');
  db.close();
})();
